
# This is the server logic for a Shiny web application.
# You can find out more about building applications with Shiny here:
#
# http://shiny.rstudio.com
#

library(shiny)
library(AppliedPredictiveModeling)
library(caret)
library(ggplot2)
library(Hmisc)

createHist <- function(seedVal = 975
                       , crossValSize = .75
                       , regressor = "Water"){
  data(concrete)
  set.seed(seedVal)
  inTrain = createDataPartition(mixtures$CompressiveStrength
                                , p = crossValSize)[[1]]
  training = mixtures[ inTrain,]
  testing = mixtures[-inTrain,]
  return(hist(training[,regressor], main = regressor))
}

createPlot <- function(seedVal = 975
                       , crossValSize = .75
                       , regressor = "Water"
                       , numBins = 4){
  set.seed(seedVal)
  inTrain = createDataPartition(mixtures$CompressiveStrength, p = crossValSize)[[1]]
  training = mixtures[ inTrain,]
  testing = mixtures[-inTrain,]
  
  df <- training
  cut_1 <- cut2(df[,regressor],g = numBins)
  q <- qplot(data = df
             , y = CompressiveStrength
             , main = regressor
             , colour = cut_1)
  return(q)
}

shinyServer(function(input, output) {

  output$sliderInputUI <- renderUI({
    if (input$outputType != "Histogram") {
      sliderInput("numBins",
                   "# of stratifiers:",
                   min = 1,
                   max = 10,
                   value = 4)
    }
  })

  output$showInstructions <- renderUI({
    if (input$instructionsYN != "No") {
      return(
        list(div(style= "margin-left: 30px;"
             ,h3("Instructions")
             ,p("If you wish to turn off these instructions, please set the 'Show Instructions' flag below to 'No'")
             ,p(strong("warning: the user of this application is assumed to have taken the Coursera Course 'Practical Machine Learning'"))
             ,p("This application gives the end user the ability to analyze 
                the 'concrete' dataset packages with the 'AppliedPredictiveModeling' package
                available from the CRAN repository.")
             ,p("The application defines two distinct sets of charts, histograms and scatter charts of
                a cross validation sample of the information")
             ,h4("General")
             ,p("This tool selects a sample from the provided concrete dataset. The user selects a 
                seed value which then updates the random sample. The sample is selected using the 'createDataPartition' 
                function from the caret package. The user additionally sets the percentage of the training
                data set to use as the training set. The value can be set from 10 to 90%.")
             ,h4("Histograms")
             ,p("When the user selects histogram, a histogram of the selected regressor is created using a default of 
                set of bins generated by the R 'hist' function.")
             ,h4("Scatter Plots")
             ,p("When the user selects scatter plot, a plot of the sequenced values of the regressor are printed
                against the X access and the value for 'Compressive Strength' on the y axis. The values are further color 
                coded by stratified ranges in order to determine if there may be a relationship between the
                strata and the regressor. The stratification level is presented to the user only when they select
                the scatter plot drop down, otherwise it remains hidden.")
        )

        )
      )
    }
  })
  
  
  output$distPlot <- renderPlot({

    if(input$outputType == "Histogram"){
        # Draw a histogram
        createHist(input$seedVal
                 , input$dataCut/100
                 , input$regressorCol)
      } else {
        # Draw a scatter plot
        createPlot(input$seedVal
               , input$dataCut/100
               , input$regressorCol
               , input$numBins)
      }
  })

})
